////

|metadata|
{
    "name": "igchartview-financial-price-series",
    "controlName": ["IGChartView"],
    "tags": ["Charting","Getting Started"],
    "guid": "57df4330-53b2-452b-8f12-96e2f0c110b5",  
    "buildFlags": [],
    "createdOn": "2012-05-21T14:04:20.3952427Z"
}
|metadata|
////

= Financial Price Series

=== Introduction

Used to plot stock prices, the  _IGChartView_™’s financial price series show a stock's high, low, open, and close prices over time. It can also display trend lines for stock prices. The financial price series is often used in combination with a number of other financial indicators to show price trends.

=== Topics

The  _IGChartView_   control supports the following types of financial price series:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:igchartview-financial-price-series-candlestick.html[Financial Price Series in Candlestick Mode]
|This topic provides a conceptual overview of the Financial Price series in Candlestick mode in the _IGChartView_ control and uses a code sample to demonstrate how to add it the chart view.

| link:igchartview-financial-price-series-ohlc.html[Financial Price Series in OHLC Mode]
|This topic provides a conceptual overview of the Financial Price series in OHLC mode in the _IGChartView_ control and uses a code example to demonstrate how to add the chart type to the chart view.

|====