////

|metadata|
{
    "name": "igflowlayoutview-layouts",
    "tags": ["Getting Started","How Do I","Layouts"],
    "controlName": ["IGFlowLayoutView"],
    "guid": "a3c6e3ad-847f-4017-a3ec-fb2e52b86c61",  
    "buildFlags": [],
    "createdOn": "2014-03-18T12:14:39.1020957Z"
}
|metadata|
////

= Layouts

== Topic Overview

=== Purpose

This topic provides a conceptual overview of layouts available with the  _IGFlowLayoutView_™ control.

=== In this topic

This topic contains the following sections:

* <<_Ref255107368, Layouts >>
* <<_Ref255107412, Related Content >>

[[_Ref255107368]]
== Layouts

[[_Ref329132134]]

=== Introduction

The  _IGFlowLayoutView_   supports 2 layouts, horizontal and vertical. Horizontal results in the  _IGFlowLayoutView_   scrolling horizontally, but not vertically. Cells are laid out top-to-bottom and then left-to-right.

For example:

1 3 5 7 →

2 4 6 8

Vertical results in the  _IGFlowLayoutView_   scrolling vertically, but not horizontally. Cells are laid out left-to-right and then top-to-bottom.

For example:

1 2 3 4

5 6 7 8

↓

To change the  _IGFlowLayoutView_   layout, set the `layoutType` property to one of the following enumerations:

* `IGFlowLayoutTypeVertical`
* `IGFlowLayoutTypeHorizontal`

[[_Ref324841253]]
[[_Ref255107412]]
== Related Content

=== Topics

The following topic provides additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:igflowlayoutview.html[IGFlowLayoutView]
|This topic serves as a gateway to the features and functionality of the _IGFlowLayoutView_ control.

|====