////

|metadata|
{
    "name": "igslidetabview-pulsing-a-tab-item",
    "tags": ["How Do I","Getting Started"],
    "controlName": ["IGSlideTabView"],
    "guid": "f7d56a38-3fd3-4086-91e7-ec03d962b748",  
    "buildFlags": [],
    "createdOn": "2014-03-18T13:53:50.1434758Z"
}
|metadata|
////

= Pulsing a Tab Item

== Topic Overview

=== Purpose

This topic provides an overview of pulsing a tab item on the  _IGSlideTabView_™ control, and using a code example to demonstrate its usage.

=== In this topic

This topic contains the following sections:

* <<_Ref324841248, Introduction >>
* <<_Ref248895787, Pulsing a Tab Item – Code Example >>

** <<_Ref327344209,Description>>
** <<_Ref327523606,Prerequisites>>
** <<_Ref327344217,Code>>

* <<_Ref215823716, Related Content >>

[[_Ref324841248]]
== Introduction

=== Pulsing a tab summary

Use pulses to draw attention to a tab item, when using the default tab view, by calling the `pulseTab:` method found on the  _IGSlideTabView_  . This method directs your focus on the tab item and generates a pulse effect, by repeatedly ramping the brightness of the tab item shape layer’s fill color down to 0.5 and then back up to 1.0 a total of 5 times.

When adopting the  _IGSlideTabViewDelegate_   protocol you may override or even cancel the pulse animation by using the `slideTabView:tabWillPulse:` method. This method expects a return of either `YES` or `NO` indicating whether or not to allow the pulse. To override the animation, create your own attention grabbing effect inside the `pulseTab:` method and return `NO`.

[[_Ref248895787]]
[[_Ref324841253]]
== Pulsing a Tab Item – Code Example

[[_Ref327344209]]

=== Description

The code example below creates and adds a tab item to the  _IGSlideTabView_   and then pulses the tab item after a 2 second delay.

[[_Ref327523606]]

=== Prerequisites

This code example requires the inclusion of the  __IG__  framework; details about how to add this framework are available in the link:iggridview-adding-the-ig-framework-file.html[Adding the IG Framework File] topic.

[[_Ref327344217]]

=== Code

*In Objective-C:*

[source,csharp]
----
IGSlideTabView *slideTabView;
IGSlideTabItem *tabItem;
- (void)viewDidLoad
{
    [super viewDidLoad];
    self.view.backgroundColor = [UIColor whiteColor];
    slideTabView = [[IGSlideTabView alloc] initWithFrame:self.view.bounds];
    slideTabView.autoresizingMask = UIViewAutoresizingFlexibleHeight|UIViewAutoresizingFlexibleWidth;
    [self.view addSubview:slideTabView];
    tabItem = [IGSlideTabItem tabWithLocation:IGSlideTabLocationBottom title:@"Example" tabView:nil contentView:nil];
    tabItem.contentSize = [IGSlideTabContentSize sizeWithPercentageWidth:0.3 percentageHeight:0.3];
    [slideTabView addTab:tabItem];
    [self performSelector:@selector(pulseTab) withObject:nil afterDelay:2.0];
}
- (void)pulseTab
{
    [slideTabView pulseTab:tabItem];
}
----

*In C#:*

[source,csharp]
----
IGSlideTabView slideTabView;
IGSlideTabItem tabItem;
public override void ViewDidLoad ()
{
      base.ViewDidLoad ();
      this.View.BackgroundColor = UIColor.White;
      slideTabView = new IGSlideTabView ();
      slideTabView.Frame = this.View.Bounds;
      slideTabView.AutoresizingMask = UIViewAutoresizing.FlexibleWidth | UIViewAutoresizing.FlexibleHeight;
      this.View.Add (slideTabView);
      tabItem = new IGSlideTabItem ();
      tabItem.TabLocation = IGSlideTabLocation.IGSlideTabLocationBottom;
      tabItem.Title = "Example";
      tabItem.ContentSize = IGSlideTabContentSize.CreatePercentageSize (0.3f, 0.3f);
      slideTabView.AddTab(tabItem);
      this.PerformSelector (new MonoTouch.ObjCRuntime.Selector ("PulseTab"), null, 2.0f);
}
[Export("PulseTab")]
public void PulseTab()
{
      slideTabView.PulseTab (tabItem);
}
----

[[_Ref215823716]]
== Related Content

=== Topics

The following topic provides additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:igslidetabview.html[IGSlideTabView]
|The topics in this group cover enabling, configuring, and using the _IGSlideTabView_ control’s supported features.

|====