////

|metadata|
{
    "name": "ios-getting-support",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "f05df2b6-0cad-471c-aba1-ef5885d12e0c",  
    "buildFlags": [],
    "createdOn": "2012-08-17T17:18:57.5679929Z"
}
|metadata|
////

= Getting Support

If you own a copy of Infragistics® {ProductNameVersion}, you are entitled to certain benefits regarding support services offered by Infragistics.

For issues related to your account, product ownership, or registration, please e-mail Registrations@Infragistics.com. Include your name and product key (if known) so that we may better assist you. You can also call (609) 448-2000 9 a.m. to 5 p.m., Monday to Friday, EST US.

*Available Support Options*

[start=1]
. link:http://community.infragistics.com/[Community Site] - This user friendly area combines blogs, articles, media and code samples as well as peer to peer forums in one central location.
[start=2]
. Developer support engineers are available to help you with your issues.

For more information on available support options, see link:http://www.infragistics.com/support/default.aspx#SupportOptions[Infragistics Support].

*Before Contacting Technical Support*

_Have a Profile:_

Visit the "My Infragistics" area of link:https://www.infragistics.com/login.aspx?ReturnUrl=/my-account/keys-and-downloads/[Infragistics' Web site], and create a link:https://www.infragistics.com/my-account/register?ReturnUrl=/my-account/keys-and-downloads/[Member Profile]. It is important that your most current information is entered into your Member Profile. For more information see, Creating a Member Profile below.

_Register the Product:_

After creating a Member Profile, register your Product Key to your MemberID by visiting the Product Registration page. Your MemberID is connected to your personal profile. Your registration identifies you as the active developer entitled to use and request support for the Infragistics product you have registered.

_Have the following information available:_

Have your member profile information and product key (if known) available.

*Checking Your Support Correspondence*

You can check your support correspondence by logging into the My Infragistics area of the Infragistics Web site using your member profile information.

*Checking the Product Life Cycle*

Infragistics Product Life Cycle contains information that is related to each product release, and helps you keep track of items such as support period. This information is available in PDF format and lists information such as:

* name and version of the Infragistics tools
* product maintenance (bug fix) period
* product support period
* product status

For more information, see link:http://www.infragistics.com/help/product-lifecycle/[Product Lifecycle].

== Creating a Member Profile

*Benefits*

[start=1]
. Creating a member profile will ensure that our Support Service Department can deliver support correspondence and subscription upgrades to you.
[start=2]
. Registering your product key with Infragistics provides you with superior technical support services quickly and conveniently.

*What Information Can Be Checked*

After logging in to the support site with your member key, you'll be able to view vital information including product keys and subscription service and status.

*Support Requirements*

While the Community site, forums, online documentation and samples are free to all members, you must have valid priority support to access phone support.

*How to Create a Member Profile*

From the following link link:https://www.infragistics.com/my-account/register?ReturnUrl=/my-account/keys-and-downloads/[here] to enter your information.

*How to Log In*

After signing up with your Username and Password, you can log into your account from this following link link:https://www.infragistics.com/login.aspx?ReturnUrl=/my-account/keys-and-downloads/[here]. This can be done by entering the information. It is important that your most current information is entered into your Member Profile.